class ZCX_DBGL_TESTCASE definition
  public
  inheriting from CX_STATIC_CHECK
  create public .

public section.

  constants DUPLICATE_TESTCASE type SOTR_CONC value '005056914D751EE99886C50523FD3A6D' ##NO_TEXT.
  constants VARIABLE_NOT_FOUND type SOTR_CONC value '005056914D751EE99887164588613A6D' ##NO_TEXT.
  constants TESTCASE_NOT_FOUND type SOTR_CONC value '005056914D751EE99887164588615A6D' ##NO_TEXT.
  constants TABLE_LINE_TYPE_NOT_SUPPORTED type SOTR_CONC value '005056914D751EE99887164588617A6D' ##NO_TEXT.
  constants NO_FUNCTION_MODULE type SOTR_CONC value '0050569AC5931EDA90D4F3A3D7E900D9' ##NO_TEXT.
  data KEY_TESTCASE type ZDBGL_KEY_TESTCASES .
  data PROGRAM type PROGRAM .
  data VARIABLE type STRING .
  data LINETYPE type ABAP_TYPEKIND .

  methods CONSTRUCTOR
    importing
      !TEXTID like TEXTID optional
      !PREVIOUS like PREVIOUS optional
      !KEY_TESTCASE type ZDBGL_KEY_TESTCASES optional
      !PROGRAM type PROGRAM optional
      !VARIABLE type STRING optional
      !LINETYPE type ABAP_TYPEKIND optional .
protected section.
private section.
ENDCLASS.



CLASS ZCX_DBGL_TESTCASE IMPLEMENTATION.


  method CONSTRUCTOR.
CALL METHOD SUPER->CONSTRUCTOR
EXPORTING
TEXTID = TEXTID
PREVIOUS = PREVIOUS
.
me->KEY_TESTCASE = KEY_TESTCASE .
me->PROGRAM = PROGRAM .
me->VARIABLE = VARIABLE .
me->LINETYPE = LINETYPE .
  endmethod.
ENDCLASS.
