CLASS smoke_test_copy DEFINITION FOR TESTING
  DURATION SHORT RISK LEVEL HARMLESS.

  PRIVATE SECTION.
    DATA: cut TYPE REF TO zdbgl_copy_to_tdc.

    METHODS setup
      RAISING cx_static_check.

    METHODS copy_all_parameters FOR TESTING
      RAISING cx_static_check.

ENDCLASS.

CLASS smoke_test_copy IMPLEMENTATION.

  METHOD setup.

    DATA(tdc) = cl_apl_ecatt_tdc_api=>get_instance( i_testdatacontainer = 'ZDBGL_UNIT_TEST_CONTAINER'
      i_write_access = abap_true i_testdatacontainer_version = 1 ).

    TRY.
        tdc->delete_variant( 'COPY_TO_TDC' ).
        tdc->commit_changes( ).
        COMMIT WORK AND WAIT.
        ##NO_HANDLER
      CATCH cx_ecatt_tdc_access.
    ENDTRY.

  ENDMETHOD.

  METHOD copy_all_parameters.
    DATA recorded_values TYPE string.

    recorded_values = '{"VAR_I":"BQAAAA==","VAR_STRING":"YSBzYW1wbGUgc3RyaW5n","VAR_CHARACTER":"Q0hBUkFDVCAgIA==","STRUCT":"AgAAAGNoYXJhICAgICAAAA==",' &&
    '"TABLE_STRUC_TYPE":["ICAgTEggMDMwMDAwMDAwMDAwAAAAAAAAAAwgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAADCAgIAAAAAAAAAAAAAAAAAAAAAA=","ICAgTEggMDM1MDAwMDAwMDAwAAAAAAAAAAwgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAADCAgIAAAAAAAAAAAAAAAAAAAAAA="],' &&
    '"HASHED_TABLE":["ICAgTEggMDMwMDAwMDAwMDAwAAAAAAAAAAwgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAADCAgIAAAAAAAAAAAAAAAAAAAAAA=","ICAgTEggMDM1MDAwMDAwMDAwAAAAAAAAAAwgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAADCAgIAAAAAAAAAAAAAAAAAAAAAA="],' &&
    '"COM_STRUCT":"AwAAAAAAAADSAAAALQAAAA==","TABLE_SIMPLE_TYPE":["AQAAAA==","AgAAAA=="],"TABLE_COM_TYPE":[["ICAgTEggMDMwMDAwMDAwMDAwAAAAAAAAAAwgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAADCAgIAAAAAAAAAAAAAAAAAAAAAA=",' &&
    '"ICAgTEggMDM1MDAwMDAwMDAwAAAAAAAAAAwgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAADCAgIAAAAAAAAAAAAAAAAAAAAAA="],["ICAgTEggMDMwMDAwMDAwMDAwAAAAAAAAAAwgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAADCAgIAAAAAAAAAAAAAAAAAAAAAA=",' &&
    '"ICAgTEggMDM1MDAwMDAwMDAwAAAAAAAAAAwgICAgICAgICAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAADCAgIAAAAAAAAAAAAAAAAAAAAAA="]]}'.

    DATA(recorder) = NEW zdbgl_getter( values = recorded_values
      program = 'ZDBGL_UNIT_TEST' ).

    DATA(cut) = NEW zdbgl_copy_to_tdc( tdc = 'ZDBGL_UNIT_TEST_CONTAINER'
      tdc_version = 1 ).

    cut->copy_all_parameter( variant = 'COPY_TO_TDC'
      recorded_variables = recorder ).
    cut->save( ).
    COMMIT WORK.

  ENDMETHOD.

ENDCLASS.
